set-resources:
    build_minimap_index:
        cpus_per_task: 4
        mem_mb_per_cpu: 3600
        partition: smp
        runtime: 60

    map_reads:
        cpus_per_task: 20
        mem_mb_per_cpu: 1800
        partition: smp
        runtime: 60

    sam_sort:
        cpus_per_task: 8
        mem_mb_per_cpu: 1800
        partition: smp
        runtime: 30

    sam_index:
        cpus_per_task: 8
        mem_mb_per_cpu: 1800
        partition: smp
        runtime: 30
        
    count_reads:
        cpus_per_task: 8
        mem_mb_per_cpu: 1800
        partition: smp
        runtime: 60

    de_analysis:
        cpus_per_task: 4
        mem_mb_per_cpu: 5000
        partition: smp
        runtime: 60
