---
## General Workflow Parameters:

# Name of the Workflow:
workflow: "workflow-transcriptome-de_phe"

inputdir: "/lustre/project/m2_jgu-ngstraining/rna_long_reads/rna_data"
# Results directory:
resdir: "/lustre/projects/m2_zdvhpc/meesters/transcriptome"
# Repository URL:
repo: ""

## Workflow-specific Parameters:

# Transcriptome fasta
transcriptome: "/lustre/miifs01/project/m2_jgu-ngstraining/rna_long_reads/transcriptome/Crip_CDS.rename.fa"
# Annotation GFF/GTF
annotation: "/lustre/miifs01/project/m2_jgu-ngstraining/rna_long_reads/transcriptome/Crip_CDS.rename.gff"
# these samples ought to contain all samples comprising of the
# 1st trait or condition (e.g. control samples)
condition_a_identifier: "female" # your trait 

# these samples ought to contain all samples comprising of the
# 2nd trait or condition (e.g. treated samples)
condition_b_identifier: "male" # your trait

# Minimap2 indexing options
minimap_index_opts: ""

# Minimap2 mapping options
minimap2_opts: ""

# Maximum secondary alignments
maximum_secondary: 100

# Secondary score ratio (-p for minimap2)
secondary_score_ratio: 1.0

# Salmon library type
salmon_libtype: "U"

# Count filtering options - customize these according to your experimental design:

# Genes expressed in minimum this many samples
min_samps_gene_expr: 3
# Transcripts expressed in minimum this many samples
min_samps_feature_expr: 1
# Minimum gene counts
min_gene_expr: 10
# Minimum transcript counts
min_feature_expr: 3

# This section defines the deseq2 plot and data handling parameters
#
# The (log2) log fold change under the null hypothesis. (default: 0).
lfc_null: 0.1
#
# The alternative hypothesis for computing wald p-values. By default, 
# the normal Wald test assesses deviation of the estimated log fold 
# change from the null hypothesis, as given by lfc_null. 
# One of ["greaterAbs", "lessAbs", "greater", "less"] or None. 
# The alternative hypothesis corresponds to what the user wants to 
# find rather than the null hypothesis. (default: None).
alt_hypothesis: "greaterAbs"
#
# The marker size in points**2 (typographic points are 1/72 in.). 
# Default is rcParams['lines.markersize'] ** 2.# minimum count to 
# be considered for subsequent analysis
point_width: 20
#
#
mincount: 10
#
# in addition to the full heatmap, plot the top number of different 
# values, ranked by the top ratio between the two traits
threshold_plot: 10
#
# the heatmap color map
# see https://seaborn.pydata.org/tutorial/color_palettes.htm for an overview
colormap: "flare" 

